// <auto-generated />
using System;
using DataAccessLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(DataAccesContext))]
    [Migration("20251111173534_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EntityLayer.Concrete.Alerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdTipoAlerta")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("lectura")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("IdTipoAlerta");

                    b.ToTable("Alertas");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Audiencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Audiencia");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "Público General"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "Consultoras"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "Colaboradores"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Descripcion = "Medios"
                        });
                });

            modelBuilder.Entity("EntityLayer.Concrete.Brief", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DeterminarEstadoEstadoId")
                        .HasColumnType("integer");

                    b.Property<string>("DirigidoA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EstatusBriefId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LinksReferencias")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Objetivo")
                        .HasColumnType("text");

                    b.Property<bool>("PlanComunicacion")
                        .HasColumnType("boolean");

                    b.Property<string>("RutaArchivo")
                        .HasColumnType("text");

                    b.Property<int>("TipoBriefId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EstatusBriefId");

                    b.HasIndex("TipoBriefId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Briefs");
                });

            modelBuilder.Entity("EntityLayer.Concrete.EstatusBrief", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EstatusBriefs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "En Revisión"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "Aprobado"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "Rechazado"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Descripcion = "Programado"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Descripcion = "Entregado"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Descripcion = "Finalizado"
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Descripcion = "En Pausa"
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            Descripcion = "Cancelado"
                        });
                });

            modelBuilder.Entity("EntityLayer.Concrete.EstatusMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EstatusMateriales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "En Revisión"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "Falta Información"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "Aprobado"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Descripcion = "Programado"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Descripcion = "Entregado"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Descripcion = "Inicio de Ciclo"
                        });
                });

            modelBuilder.Entity("EntityLayer.Concrete.Formato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Formato");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "Digital"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "Impreso"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "Video"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Descripcion = "Audio"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Descripcion = "Redes Sociales"
                        });
                });

            modelBuilder.Entity("EntityLayer.Concrete.HistorialMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentarios")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EstatusMaterialId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("HistorialMateriales");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AudienciaId")
                        .HasColumnType("integer");

                    b.Property<int>("BriefId")
                        .HasColumnType("integer");

                    b.Property<string>("Ciclo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EstatusMaterialId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FormatoId")
                        .HasColumnType("integer");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PrioridadId")
                        .HasColumnType("integer");

                    b.Property<string>("Responsable")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AudienciaId");

                    b.HasIndex("BriefId");

                    b.HasIndex("EstatusMaterialId");

                    b.HasIndex("FormatoId");

                    b.HasIndex("PrioridadId");

                    b.ToTable("Materiales");
                });

            modelBuilder.Entity("EntityLayer.Concrete.MaterialPCN", b =>
                {
                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<int>("PCNId")
                        .HasColumnType("integer");

                    b.HasKey("MaterialId", "PCNId");

                    b.HasIndex("PCNId");

                    b.ToTable("MaterialPCN");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Icono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Participante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BriefId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BriefId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Participantes");
                });

            modelBuilder.Entity("EntityLayer.Concrete.PCN", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PCN");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "Lanzamiento"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "Continuidad"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "Promoción"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Descripcion = "Institucional"
                        });
                });

            modelBuilder.Entity("EntityLayer.Concrete.Prioridad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Prioridad");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "Baja"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "Media"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "Alta"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Descripcion = "Urgente"
                        });
                });

            modelBuilder.Entity("EntityLayer.Concrete.Proyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BriefId")
                        .HasColumnType("integer");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("RequierePlan")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("BriefId")
                        .IsUnique();

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("EntityLayer.Concrete.RetrasoMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<int>("MotivoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.ToTable("RetrasoMateriales");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Solicitante"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Productor"
                        });
                });

            modelBuilder.Entity("EntityLayer.Concrete.TipoAlerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TipoAlerta");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "Nuevo Proyecto"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "Cambio de Estado"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "Actualización"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Descripcion = "Nuevo Material"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Descripcion = "Material Entregado"
                        });
                });

            modelBuilder.Entity("EntityLayer.Concrete.TipoBrief", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TiposBrief");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "Plan de Comunicación"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "Materiales"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "Campaña"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Descripcion = "Evento"
                        });
                });

            modelBuilder.Entity("EntityLayer.Concrete.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("CambioContrasena")
                        .HasColumnType("boolean");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Estatus")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<bool>("SolicitudRegistro")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Alerta", b =>
                {
                    b.HasOne("EntityLayer.Concrete.TipoAlerta", "TipoAlerta")
                        .WithMany("Alertas")
                        .HasForeignKey("IdTipoAlerta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoAlerta");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Brief", b =>
                {
                    b.HasOne("EntityLayer.Concrete.EstatusBrief", "EstatusBrief")
                        .WithMany("Briefs")
                        .HasForeignKey("EstatusBriefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.TipoBrief", "TipoBrief")
                        .WithMany("Briefs")
                        .HasForeignKey("TipoBriefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Usuario", "Usuario")
                        .WithMany("Briefs")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstatusBrief");

                    b.Navigation("TipoBrief");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EntityLayer.Concrete.HistorialMaterial", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Material", "Material")
                        .WithMany("Historiales")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Material", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Audiencia", "Audiencia")
                        .WithMany("Materiales")
                        .HasForeignKey("AudienciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Brief", "Brief")
                        .WithMany("Materiales")
                        .HasForeignKey("BriefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.EstatusMaterial", "EstatusMaterial")
                        .WithMany()
                        .HasForeignKey("EstatusMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Formato", "Formato")
                        .WithMany("Materiales")
                        .HasForeignKey("FormatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Prioridad", "Prioridad")
                        .WithMany("Materiales")
                        .HasForeignKey("PrioridadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Audiencia");

                    b.Navigation("Brief");

                    b.Navigation("EstatusMaterial");

                    b.Navigation("Formato");

                    b.Navigation("Prioridad");
                });

            modelBuilder.Entity("EntityLayer.Concrete.MaterialPCN", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Material", "Material")
                        .WithMany("MaterialPCNs")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.PCN", "PCN")
                        .WithMany("MaterialPCNs")
                        .HasForeignKey("PCNId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("PCN");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Menu", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Rol", "Rol")
                        .WithMany("Menus")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Participante", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Brief", "Brief")
                        .WithMany()
                        .HasForeignKey("BriefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Usuario", "Usuario")
                        .WithMany("Participantes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Brief");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Proyecto", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Brief", "Brief")
                        .WithOne("Proyecto")
                        .HasForeignKey("EntityLayer.Concrete.Proyecto", "BriefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brief");
                });

            modelBuilder.Entity("EntityLayer.Concrete.RetrasoMaterial", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Material", "Material")
                        .WithMany("Retrasos")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Usuario", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Rol", "UserRol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserRol");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Audiencia", b =>
                {
                    b.Navigation("Materiales");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Brief", b =>
                {
                    b.Navigation("Materiales");

                    b.Navigation("Proyecto")
                        .IsRequired();
                });

            modelBuilder.Entity("EntityLayer.Concrete.EstatusBrief", b =>
                {
                    b.Navigation("Briefs");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Formato", b =>
                {
                    b.Navigation("Materiales");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Material", b =>
                {
                    b.Navigation("Historiales");

                    b.Navigation("MaterialPCNs");

                    b.Navigation("Retrasos");
                });

            modelBuilder.Entity("EntityLayer.Concrete.PCN", b =>
                {
                    b.Navigation("MaterialPCNs");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Prioridad", b =>
                {
                    b.Navigation("Materiales");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Rol", b =>
                {
                    b.Navigation("Menus");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("EntityLayer.Concrete.TipoAlerta", b =>
                {
                    b.Navigation("Alertas");
                });

            modelBuilder.Entity("EntityLayer.Concrete.TipoBrief", b =>
                {
                    b.Navigation("Briefs");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Usuario", b =>
                {
                    b.Navigation("Briefs");

                    b.Navigation("Participantes");
                });
#pragma warning restore 612, 618
        }
    }
}
